DEBUG : False
INIT_VAL : True
GREEDY_BASELINE : True
SAVE_BEST_METRIC : True # to save nothing : = False and checkpoint_freq = 0
captions_type : "blip2mistral" #coco, (mistral, mistral_4), blip2mistral
train_method : "cider" # (discriminative, cider, mle)
prefix_len : 10
warmup_ratio : 0.034
official_clipcap_weights : /home/manugaur/official_clipcap/coco_weights.pt

opts: 
  baseline : mean
  n_epochs : 20
  batch_size : 180
  lr :  1e-7 #2e-5
  max_len : 50
  checkpoint_freq : 0
  num_workers : 16
  dataset_dir : /home/manugaur/coco
  mle_model_path : /home/manugaur/EGG/checkpoints/blip2mistral/mle_len_50/best.pt
  checkpoint_dir : /home/manugaur/EGG/checkpoints/blip2mistral/cider_g_len_50
    
WANDB :
  logging : True
  sweep : False
  sweep_id: ""
  sweep_run_count : 100
  entity : "manugaur"
  project : "emergent_captioner"
  run_name : "cider_g_len_50_blip2mistral"

