DEBUG : False
INIT_VAL : True
GREEDY_BASELINE : True
SAVE_BEST_METRIC : True # to save nothing : = False and checkpoint_freq = 0
captions_type : "mistral_4" #coco, (mistral, mistral_4), blip_holistic
train_method : "mle" # (discriminative, cider, mle)
prefix_len : 10
warmup_ratio : 0.034
official_clipcap_weights : /home/manugaur/official_clipcap/coco_weights.pt
num_workers : 16
CAPS_PER_IMG_train: 4
CAPS_PER_IMG_val: 4

opts: 
  baseline : mean
  n_epochs : 10
  batch_size : 40 #10 for ada
  lr :  2e-5
  max_len : 50
  checkpoint_freq : 1
  num_workers : 16
  dataset_dir : /home/manugaur/coco
  checkpoint_dir : /home/manugaur/EGG/checkpoints/coco/mle_len_50  #
    
WANDB :
  logging : False
  sweep : False
  sweep_id: ""
  sweep_run_count : 100
  entity : "manugaur"
  project : "emergent_captioner"
  run_name : "mle_len_50_mistral4_ada_no_ddp" # "mle_len_50_mistral_4"
 
inference : 
  batch_size : 180
  output_dir : /home/manugaur/EGG/inference_preds/
  #captions_type, debug, init_val


#checkpoint_dir, debug,init_val, logging, bsz, wandb_name